export const getVersions = 'getVersions'
export const getVersion = 'getVersion'
export const postVersion = 'postVersion'
export const putVersion = 'putVersion'
export const delVersion = 'delVersion'
export const delRow = 'delRow'
